"""Statistical analysis modules for Soma."""

from .proven import (
    # Result types
    ConfidenceInterval,
    CircadianResult,
    WeeklyActivityResult,
    TrendResult,
    AnomalyResult,
    AnomalyDay,
    HRVResult,
    SpO2Result,
    # Analysis functions
    analyze_circadian_rhythm,
    analyze_weekly_activity,
    analyze_long_term_trend,
    detect_anomalies,
    analyze_hrv,
    analyze_spo2,
)

from .advanced import (
    # Result types
    CorrelationPair,
    CorrelationMatrix,
    LaggedCorrelation,
    RecoveryModel,
    SeasonalComponent,
    SeasonalAnalysis,
    ReadinessScore,
    ReadinessModel,
    # Analysis functions
    analyze_correlations,
    analyze_recovery,
    analyze_seasonality,
    build_readiness_model,
    compute_readiness_scores,
    get_readiness_summary,
)

from .stability import (
    # Result types
    ConvergencePoint,
    ConvergenceAnalysis,
    TemporalStability,
    DriftResult,
    SampleAdequacy,
    StabilityReport,
    # Analysis functions
    analyze_convergence,
    analyze_temporal_stability,
    analyze_drift,
    analyze_sample_adequacy,
    generate_stability_report,
)

from .derived import (
    # Tier 1: High Value
    NocturnalDipResult,
    TrainingLoadResult,
    AutonomicBalanceResult,
    StressIndexResult,
    BehavioralRegularityResult,
    # Tier 2: Personal Tracking
    CardiovascularEfficiencyResult,
    StrainIndexResult,
    RecoveryTrendResult,
    CircadianAmplitudeResult,
    EnergyDistributionResult,
    # Tier 3: Experimental
    NightRestlessnessResult,
    PhysiologicalCoherenceResult,
    DerivedMetricsReport,
    # Analysis functions
    analyze_nocturnal_dip,
    analyze_training_load,
    analyze_autonomic_balance,
    analyze_stress_index,
    analyze_behavioral_regularity,
    analyze_cardiovascular_efficiency,
    analyze_strain_index,
    analyze_recovery_trend,
    analyze_circadian_amplitude,
    analyze_energy_distribution,
    analyze_night_restlessness,
    analyze_physiological_coherence,
    generate_derived_metrics_report,
)

from .sleep import (
    # Result types
    NightlySleep,
    SleepArchitectureBaseline,
    SleepArchitectureDeviation,
    SleepArchitectureTrend,
    SleepArchitectureReport,
    # Analysis functions
    compute_nightly_sleep,
    compute_sleep_baseline,
    compute_sleep_deviation,
    analyze_sleep_trend,
    generate_sleep_report,
)

from .daylight import (
    # Result types
    DailyDaylight,
    DaylightBaseline,
    DaylightDeviation,
    DaylightTrend,
    DaylightSleepCorrelation,
    DaylightReport,
    # Analysis functions
    compute_daily_daylight,
    compute_daylight_baseline,
    compute_daylight_deviation,
    analyze_daylight_trend,
    compute_daylight_sleep_correlation,
    generate_daylight_report,
)

from .vo2max import (
    # Result types
    VO2MaxMeasurement,
    VO2MaxPercentile,
    FitnessAge,
    VO2MaxTrend,
    MortalityRisk,
    TrainingResponse,
    VO2MaxReport,
    # Analysis functions
    compute_percentile,
    compute_fitness_age,
    compute_mortality_risk,
    analyze_trend as analyze_vo2max_trend,
    assess_training_response,
    generate_vo2max_report,
)

from .body_composition import (
    # Result types
    BMIResult,
    BodyFatPercentile,
    WeightMeasurement,
    WeightTrend,
    BodyCompositionChange,
    FitnessCorrelation,
    BodyCompositionReport,
    BodyCompositionSummary,
    # Analysis functions
    compute_bmi,
    compute_body_fat_percentile,
    compute_body_composition,
    analyze_weight_trend,
    analyze_composition_change,
    compute_fitness_correlations,
    generate_body_composition_report,
    get_body_composition_summary,
)

from .holistic import (
    # Core result types
    Finding,
    Interconnection,
    Paradox,
    BehavioralPattern,
    RiskFactor,
    Recommendation,
    DomainScore,
    WellnessScore,
    DataAdequacy,
    HolisticInsight,
    # SpO2 analysis (high reliability: CV=2.2%, stability=98.9%)
    SpO2Analysis,
    # Mobility analysis (confound-controlled, 97% real signal)
    MobilityAnalysis,
    analyze_mobility,
    # Input types
    AnalysisInputs,
    # Utility functions
    aggregate_signals,
    compute_data_adequacy,
    compute_correlation,
    compute_detrended_correlation,
    compute_lagged_correlation,
    # Paradox detection
    detect_simpsons_paradox,
    detect_all_paradoxes,
    # Behavioral pattern detection
    detect_compensatory_exercise,
    detect_weekend_warrior,
    detect_seasonal_activity_pattern,
    detect_all_behavioral_patterns,
    # Cross-domain analysis
    find_cross_domain_interconnections,
    # Wellness score computation
    compute_cardiovascular_score,
    compute_sleep_score,
    compute_activity_score,
    compute_recovery_score,
    compute_body_composition_score,
    compute_mobility_score,
    compute_wellness_score,
    # Risk and recommendations
    synthesize_risk_factors,
    identify_protective_factors,
    generate_recommendations,
    # Main analysis function
    generate_holistic_insight,
)

from .interventions import (
    # Data structures
    Intervention,
    BiomarkerChange,
    TrendAnalysis,
    SeasonalityControl,
    InterventionImpact,
    InterventionReport,
    # Statistical functions
    compute_cohens_d,
    compute_change_confidence_interval,
    analyze_trend,
    detect_level_jump,
    # Analysis functions
    analyze_biomarker_change,
    analyze_intervention_impact,
    generate_intervention_report,
)

from .bayesian_intervention import (
    # Enums and types
    EvidenceStrength,
    # Data structures
    InterventionPrior,
    DataSufficiency,
    BiomarkerConflict,
    PriorInfluence,
    BayesianEffectEstimate,
    BayesianInterventionAnalysis,
    # Correlation adjustment (biomarker redundancy)
    CorrelationAdjustment,
    compute_correlation_adjustment,
    compute_effective_n_eigenvalue,
    compute_known_correlations,
    # Temporal confound adjustment
    TemporalAdjustment,
    compute_temporal_adjustment,
    compute_regression_to_mean,
    compute_seasonal_effect,
    estimate_reliability,
    # Prior lookup
    get_prior,
    get_mcid,
    is_clinically_meaningful,
    # Personal MCID
    compute_personal_mcid,
    is_personally_meaningful,
    # Data sufficiency
    assess_data_sufficiency,
    # Conflict detection
    detect_biomarker_conflicts,
    # Prior transparency
    compute_prior_influence,
    # Core functions
    interpret_bayes_factor,
    compute_posterior_probabilities,
    compute_effect_size_credible_interval,
    # Main analysis
    analyze_intervention_bayesian,
)

__all__ = [
    # Proven analysis
    "ConfidenceInterval",
    "CircadianResult",
    "WeeklyActivityResult",
    "TrendResult",
    "AnomalyResult",
    "AnomalyDay",
    "HRVResult",
    "SpO2Result",
    "analyze_circadian_rhythm",
    "analyze_weekly_activity",
    "analyze_long_term_trend",
    "detect_anomalies",
    "analyze_hrv",
    "analyze_spo2",
    # Advanced analysis
    "CorrelationPair",
    "CorrelationMatrix",
    "LaggedCorrelation",
    "RecoveryModel",
    "SeasonalComponent",
    "SeasonalAnalysis",
    "ReadinessScore",
    "ReadinessModel",
    "analyze_correlations",
    "analyze_recovery",
    "analyze_seasonality",
    "build_readiness_model",
    "compute_readiness_scores",
    "get_readiness_summary",
    # Stability analysis
    "ConvergencePoint",
    "ConvergenceAnalysis",
    "TemporalStability",
    "DriftResult",
    "SampleAdequacy",
    "StabilityReport",
    "analyze_convergence",
    "analyze_temporal_stability",
    "analyze_drift",
    "analyze_sample_adequacy",
    "generate_stability_report",
    # Derived metrics
    "NocturnalDipResult",
    "TrainingLoadResult",
    "AutonomicBalanceResult",
    "StressIndexResult",
    "BehavioralRegularityResult",
    "CardiovascularEfficiencyResult",
    "StrainIndexResult",
    "RecoveryTrendResult",
    "CircadianAmplitudeResult",
    "EnergyDistributionResult",
    "NightRestlessnessResult",
    "PhysiologicalCoherenceResult",
    "DerivedMetricsReport",
    "analyze_nocturnal_dip",
    "analyze_training_load",
    "analyze_autonomic_balance",
    "analyze_stress_index",
    "analyze_behavioral_regularity",
    "analyze_cardiovascular_efficiency",
    "analyze_strain_index",
    "analyze_recovery_trend",
    "analyze_circadian_amplitude",
    "analyze_energy_distribution",
    "analyze_night_restlessness",
    "analyze_physiological_coherence",
    "generate_derived_metrics_report",
    # Sleep architecture
    "NightlySleep",
    "SleepArchitectureBaseline",
    "SleepArchitectureDeviation",
    "SleepArchitectureTrend",
    "SleepArchitectureReport",
    "compute_nightly_sleep",
    "compute_sleep_baseline",
    "compute_sleep_deviation",
    "analyze_sleep_trend",
    "generate_sleep_report",
    # Daylight analysis
    "DailyDaylight",
    "DaylightBaseline",
    "DaylightDeviation",
    "DaylightTrend",
    "DaylightSleepCorrelation",
    "DaylightReport",
    "compute_daily_daylight",
    "compute_daylight_baseline",
    "compute_daylight_deviation",
    "analyze_daylight_trend",
    "compute_daylight_sleep_correlation",
    "generate_daylight_report",
    # VO2 Max analysis
    "VO2MaxMeasurement",
    "VO2MaxPercentile",
    "FitnessAge",
    "VO2MaxTrend",
    "MortalityRisk",
    "TrainingResponse",
    "VO2MaxReport",
    "compute_percentile",
    "compute_fitness_age",
    "compute_mortality_risk",
    "analyze_vo2max_trend",
    "assess_training_response",
    "generate_vo2max_report",
    # Body Composition analysis
    "BMIResult",
    "BodyFatPercentile",
    "WeightMeasurement",
    "WeightTrend",
    "BodyCompositionChange",
    "FitnessCorrelation",
    "BodyCompositionReport",
    "BodyCompositionSummary",
    "compute_bmi",
    "compute_body_fat_percentile",
    "compute_body_composition",
    "analyze_weight_trend",
    "analyze_composition_change",
    "compute_fitness_correlations",
    "generate_body_composition_report",
    "get_body_composition_summary",
    # Holistic insights
    "Finding",
    "Interconnection",
    "Paradox",
    "BehavioralPattern",
    "RiskFactor",
    "Recommendation",
    "DomainScore",
    "WellnessScore",
    "DataAdequacy",
    "HolisticInsight",
    "SpO2Analysis",
    "analyze_spo2",
    "MobilityAnalysis",
    "analyze_mobility",
    "AnalysisInputs",
    "aggregate_signals",
    "compute_data_adequacy",
    "compute_correlation",
    "compute_detrended_correlation",
    "compute_lagged_correlation",
    "detect_simpsons_paradox",
    "detect_all_paradoxes",
    "detect_compensatory_exercise",
    "detect_weekend_warrior",
    "detect_seasonal_activity_pattern",
    "detect_all_behavioral_patterns",
    "find_cross_domain_interconnections",
    "compute_cardiovascular_score",
    "compute_sleep_score",
    "compute_activity_score",
    "compute_recovery_score",
    "compute_body_composition_score",
    "compute_mobility_score",
    "compute_wellness_score",
    "synthesize_risk_factors",
    "identify_protective_factors",
    "generate_recommendations",
    "generate_holistic_insight",
    # Intervention analysis
    "Intervention",
    "BiomarkerChange",
    "TrendAnalysis",
    "SeasonalityControl",
    "InterventionImpact",
    "InterventionReport",
    "compute_cohens_d",
    "compute_change_confidence_interval",
    "analyze_trend",
    "detect_level_jump",
    "analyze_seasonality",
    "analyze_biomarker_change",
    "analyze_intervention_impact",
    "generate_intervention_report",
    # Bayesian intervention analysis
    "EvidenceStrength",
    "InterventionPrior",
    "DataSufficiency",
    "BiomarkerConflict",
    "PriorInfluence",
    "BayesianEffectEstimate",
    "BayesianInterventionAnalysis",
    # Correlation adjustment
    "CorrelationAdjustment",
    "compute_correlation_adjustment",
    "compute_effective_n_eigenvalue",
    "compute_known_correlations",
    # Temporal adjustment
    "TemporalAdjustment",
    "compute_temporal_adjustment",
    "compute_regression_to_mean",
    "compute_seasonal_effect",
    "estimate_reliability",
    # Other Bayesian functions
    "get_prior",
    "get_mcid",
    "is_clinically_meaningful",
    "compute_personal_mcid",
    "is_personally_meaningful",
    "assess_data_sufficiency",
    "detect_biomarker_conflicts",
    "compute_prior_influence",
    "interpret_bayes_factor",
    "compute_posterior_probabilities",
    "compute_effect_size_credible_interval",
    "analyze_intervention_bayesian",
]
